# Generated by Django 5.2.9 on 2026-09-22 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('item_type', models.CharField(choices=[('coin', 'Coin'), ('note', 'BankNote')], default='coin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoinOrNoteVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('mint_mark', models.CharField(help_text='e.g., Mumbai (Diamond), Noida (Dot), Calcutta (No Mark)', max_length=100)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Scarce', 'Scarce'), ('Rare', 'Rare'), ('Extremely Rare', 'Extremely Rare')], default='Rare', max_length=20)),
                ('estimated_value', models.CharField(help_text='e.g., ₹500 - ₹2,000', max_length=50)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='coins/front/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='coins/back/')),
                ('description', models.TextField(help_text='Detailed info on where to check the mint mark / unique features.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.category')),
            ],
        ),
    ]
